language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install --upgrade pip
  - pip install -e .
  - pip install --upgrade codecov pylint astroid pytest pytest-cov matplotlib
script:
  - pylint pysocialforce
  - pytest --cov=pysocialforce tests/
